#!/bin/bash
SCRIPT=${0##*/}
SCRIPT_VERSION="1.1"

shopt -s nullglob

# Define color codes
CYAN='\033[0;36m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

files=(spin2*.vsix)
count=${#files[@]}

if [ $count -eq 1 ]; then
    echo -e "${SCRIPT}: ${CYAN}Installing  ${files[0]} ...${NC}"
    (set -x;code --install-extension ${files[0]})
    elif [ $count -gt 1 ]; then
    echo -e "${SCRIPT}: ${YELLOW}There are multiple VSIX files:${NC}" >&2
    for file in "${files[@]}"; do
        echo "  - ${file}"  >&2
    done
    echo -e "${SCRIPT}: ${YELLOW}Please remove all but the one you want to install and run the script again.${NC}" >&2
else
    echo -e "${SCRIPT}: ${RED}ERROR: No VSIX files found. You might be in the wrong directory.${NC}" >&2
fi
